server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

logging:
  file:
    path: /logs
    name: app.log
  level:
    root: info
    com.wemakeprice.parser: debug
